- name: ping the server
  hosts: local
  become: true #( gives sudo access)
  tasks: #list of tasks
    - name: ping the Server
      ansible.builtin.ping:

    - name: install and run nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
